# fly.toml app configuration file generated for stagio-api on 2025-07-23T18:23:19-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stagio-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[env]
  SPRING_PROFILES_ACTIVE = "production"

[checks]
  [checks.status]
    type = "http"
    port = 8082
    path = "/actuator/health"
    interval = "10s"
    timeout = "5s"