app = "stagio-api"
primary_region = "iad"

[env]
SPRING_PROFILES_ACTIVE = "production"
SERVER_PORT = "8082"

[vm]
memory = 2048
cpu_kind = "shared"
cpus = 2

[[services]]
internal_port = 8082
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.http_checks]
path = "/actuator/health"
interval = 10000  # 10 seconds in ms
timeout = 5000    # 5 seconds in ms
grace_period = "30s"
method = "GET"
