server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
  port: 8082

spring:
  profiles:
    active: test
  mvc:
    log-request-details: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  flyway:
    defaultSchema: edge
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    jwt:
      access-secret: o5j(1m]h%'Dl3D&8£f"ah6f]t&3VtE]uej-#?65."K78"UUeEa
      refresh-secret: k[k66T8Bf'X~q+KQ27OB£3zay(9Q+4F(ydA>J'nM:DK[*XSc8B

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
