spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  security:
    jwt:
      access-secret: ${ACCESS_SECRET}
      refresh-secret: ${REFRESH_SECRET}
  management:
    endpoints:
      web:
        exposure:
          include: health

server:
  port: ${SERVER_PORT:8082}
  address: 0.0.0.0

stream:
  nginx-hostname: stream-service.fly.dev

proxy:
  transcoder:
    base-url: https://stream-service.fly.dev:3001

cors:
  allowed-headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
    - Accept-Language
    - Accept-Encoding
    - Client-Id
    - Platform
    - Access-Control-Allow-Headers
    - Access-Control-Allow-Origin
  exposed-headers:
    - Location
    - Access-Control-Allow-Origin
  allowed-origins:
    - https://stagio.live
    - https://www.stagio.live