spring:
  datasource:
    url: jdbc:postgresql://db:5433/mydb
    driverClassName: org.postgresql.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

cors:
  allowed-headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
    - Accept-Language
    - Accept-Encoding
    - Client-Id
    - Platform
    - Access-Control-Allow-Headers
    - Access-Control-Allow-Origin
  exposed-headers:
    - Location
    - Access-Control-Allow-Origin
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173