spring:
  datasource:
    url: ${DATABASE_URL}
    username: fly-user
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  security:
    jwt:
      access-secret: ${ACCESS_SECRET}
      refresh-secret: ${REFRESH_SECRET}

server:
  port: ${PORT:8082}
  address: 0.0.0.0

proxy:
  transcoder:
    base-url: http://transcoder-worker.internal:3001

cors:
  allowed-headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
    - Accept-Language
    - Accept-Encoding
    - Client-Id
    - Platform
    - Access-Control-Allow-Headers
    - Access-Control-Allow-Origin
  exposed-headers:
    - Location
    - Access-Control-Allow-Origin
  allowed-origins:
    - https://stagio.live
    - https://www.stagio.live